### PR TITLE
Fix dimensions

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**

### CODE REVIEW

**Comment by BoogieMonster1O1** [comment]
oops wrong repo

**Comment by Soyaro666** [comment]
...there is someone actually working on DimDoors?

**Comment by BoogieMonster1O1** [comment]
> ...there is someone actually working on DimDoors?

yep. since 2017
https://github.com/DimensionalDevelopment/DimDoors

**Comment by Soyaro666** [comment]
and that repo got an additional watcher. thanks ^^

**Pull request closed without merging**
